const length = require('./length');
const mass = require('./mass');
const time = require('./time');
const angle = require('./angle');
const current = require('./current');
const temp = require('./temp');
const matter = require('./matter');
const intensity = require('./intensity');
const fileSize = require('./file_size');
const energy = require('./energy');
const pressure = require('./pressure');
const force = require('./force');
const hertz = require('./hertz');
const watt = require('./watt');
const coulomb = require('./coulomb');
const volt = require('./volt');
const farad = require('./farad');
const ohm = require('./ohm');
const siemens = require('./siemens');
const weber = require('./weber');
const tesla = require('./tesla');
const henry = require('./henry');
const lux = require('./lux');
const volume = require('./volume');
const area = require('./area');


module.exports = () => {
  length();
  mass();
  time();
  angle();
  current();
  temp();
  matter();
  intensity();
  fileSize();
  energy();
  pressure();
  force();
  hertz();
  watt();
  coulomb();
  volt();
  farad();
  ohm();
  siemens();
  weber();
  tesla();
  henry();
  lux();
  volume();
  area();
};
